# Generated by Django 4.2.5 on 2024-04-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_lecture_delete_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Файл лекций', 'verbose_name_plural': 'Файлы лекций'},
        ),
    ]
