# Generated by Django 4.2.5 on 2024-04-24 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfile',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
