# Generated by Django 3.2.25 on 2024-03-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='question_file',
        ),
    ]
