# Generated by Django 3.2.25 on 2024-03-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_usertest_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='question_file',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.questionfile'),
            preserve_default=False,
        ),
    ]
