# Generated by Django 3.2.25 on 2024-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20240328_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
