# Generated by Django 4.2.5 on 2024-03-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_usertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, default='default_file', null=True, upload_to='polls/quiz/')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.questionfile'),
            preserve_default=False,
        ),
    ]
