# Generated by Django 3.2.25 on 2024-03-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questionfile_question_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to='polls/quiz/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
