# Generated by Django 4.2.5 on 2024-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_usertest_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
