# Generated by Django 4.2.5 on 2024-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_questionfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='file',
            field=models.FileField(upload_to='polls/quiz/'),
        ),
    ]
