# Generated by Django 4.2.5 on 2024-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_questionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='file',
            field=models.FileField(default=None, upload_to='polls/quiz/'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='title',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
