# Generated by Django 4.2.5 on 2024-04-08 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_alter_questionfile_file_alter_questionfile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionfile',
            options={'verbose_name': 'Файл с вопросами', 'verbose_name_plural': 'Файлы с вопросами'},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Вариант ответа пользователя', 'verbose_name_plural': 'Варианты ответов пользователя'},
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('question_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questionfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
            },
        ),
    ]
