# Generated by Django 4.2.5 on 2024-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'Инструкцию', 'verbose_name_plural': 'Инструкции'},
        ),
    ]
