# Generated by Django 4.2.5 on 2024-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_instructions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='file',
            field=models.FileField(default='', upload_to='home/instructions'),
        ),
    ]
